# This config uses industrial_ci (https://github.com/ros-industrial/industrial_ci.git).
# For troubleshooting, see README (https://github.com/ros-industrial/industrial_ci/blob/master/README.rst)

name: CI

on:
  push:
    branches: [ main, devel, ci ]
  pull_request:
    branches: [ main, devel ]
  workflow_dispatch: # allow manually starting this workflow

jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: iron, ROS_REPO: testing}
          - {ROS_DISTRO: rolling, ROS_REPO: testing}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}